schemaVersion: 2.2.2
metadata:
  name: openjdk-workspace
components:
  - name: tools
    container:
      image: quay.io/kanekoh/openjdk:ubi
      cpuRequest: 50m
      cpuLimit: 1000m
      memoryRequest: 1Gi
      memoryLimit: 4Gi
      env:
        - name: HOME
          value: "/projects/home"
