schemaVersion: 2.2.2
metadata:
  name: openjdk-workspace
components:
  - name: tools
    container:
      image: quay.io/kanekoh/openjdk:ubi
      cpuRequest: 50m
      cpuLimit: 1000m
      memoryRequest: 1Gi
      memoryLimit: 4Gi
      env:
        - name: HOME
          value: "/projects/home"
  - name: prep-workspace
    container:
      args:
        - '-c'
        - >-
          mkdir -p /projects/bin && cp /usr/bin/oc /projects/bin/oc && cp /usr/bin/kubectl /projects/bin/kubectl && if [[ -f ${HOME}/.kube/config ]]; then rm ${HOME}/.kube/config; fi
      command:
        - /bin/bash
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      mountSources: true
      sourceMapping: /projects
      memoryRequest: 128Mi
      memoryLimit: 256Mi
      cpuRequest: 10m
      cpuLimit: 200m
      env:
      - name: HOME
        value: "/projects/home"
events:
  preStart:
    - prep-workspace
